/*
 * @Author: Guifen Shangguan 
 * @Date: 2021-04-28 10:34:03 
 * @Last Modified by: Guifen Shangguan
 * @Last Modified time: 2021-04-29 15:19:05
 */
export const SET_FILENAME = 'SET_FILENAME';
export const SET_MENU_VISIBLE = 'SET_MENU_VISIBLE';
export const SET_SETTING_VISIBLE = 'SET_SETTING_VISIBLE';
export const SET_DEFAULT_FONT_SIZE = 'SET_DEFAULT_FONT_SIZE';
export const SET_CURRENT_BOOK = 'SET_CURRENT_BOOK';
export const SET_DEFAULT_FONT_FAMILY = 'SET_DEFAULT_FONT_FAMILY';
export const SET_FONT_FAMILY_VISIBLE = 'SET_FONT_FAMILY_VISIBLE';
export const SET_DEFAULT_THEME = 'SET_DEFAULT_THEME';
export const SET_BOOK_AVAILABLE = 'SET_BOOK_AVAILABLE';
export const SET_PROGRESS = 'SET_PROGRESS';
export const SET_SECTION = 'SET_SECTION';
export const SET_SECTION_PROGRESS = 'SET_SECTION_PROGRESS';
export const SET_COVER = 'SET_COVER';
export const SET_METADATA = 'SET_METADATA';
export const SET_NAVIGATION = 'SET_NAVIGATION';
export const SET_OFFSETY = 'SET_OFFSETY';
export const SET_IS_BOOKMARK = 'SET_IS_BOOKMARK';
export const SET_PAGELIST = 'SET_PAGELIST';